name: tractian
description: "Tractian Mobile Software Engineer Challenge"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  flutter_svg: ^2.0.16
  mobx: ^2.5.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/